### PR TITLE
Allow installation on non-Intel CPUs with MacOS, and improve error message for unsupported environments

### PR DESCRIPTION
**Pull request by C0urante**
Addresses https://github.com/kcctl/kcctl/issues/134

Adapted from https://github.com/kcctl/homebrew-tap/pull/3

### CODE REVIEW

**Comment by C0urante** [comment]
@gunnarmorling would you be able to take a look when you have a moment?

**Review by gunnarmorling — APPROVED** [review]
LGTM, applying. Thx! Does this require a release to homebrew, or does it pull this formula automatically without us having to do anything? That being said, it would be nice to release anyways soonish, for getting out all the recently added features.

**Comment by C0urante** [comment]
I've just tested this out with a fresh Apple Silicon laptop and the installation went off without a hitch; looks like no release is necessary. It may be necessary for users who have already tried and failed to install `kcctl` to force brew to fetch the new formula, though; haven't been able to test that scenario.

Agreed on the release--are there any issues that should qualify as blockers or do we feel like this is in a good enough state to push a new one right now?

**Comment by gunnarmorling** [comment]
Yeah, I think we're good to go for a Beta1 release. // @almiray

Chris Egerton ***@***.***> schrieb am Mo., 12. Dez. 2022,
16:06:

**Comment by gunnarmorling** [comment]
Beta1 is out: https://twitter.com/gunnarmorling/status/1602402394528448512.
A big thank you to you Chris for all your contributions to this release and
to Andres for cutting the release!

Gunnar Morling ***@***.***> schrieb am Mo., 12. Dez.
2022, 17:05:

**Pull request merged**
